language: elixir
elixir:
  - 1.2.5
  - 1.3.2
otp_release:
  - 17.1
  - 18.3
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis
